### ISSUE TITLE
Passing the address/netmask directly as integer/sockaddr_in

### ISSUE THREAD

**Issue by skateman** [Papierkorb/tuntap#2]
Would it be desired to have some extra overloads for the `add_address` and `add_netmask` methods?
It would be nice if I would be able just pass the sockaddr_in structure to them:
```crystal
def add_address(address : LibC::SockaddrIn)
  ifr = ifreq
  ifr.ifr = LibC::IfReqData.new(addr: address)

  ioctl LibC::SIOCSIFADDR, ifr
end

def add_address(address : String)
  add_address(sockaddr(address))
end
```

**Comment by Papierkorb** [comment]
Hi,

Yes that'd be great.  If you see methods that could use similar overloads then those as well.

This part of the Linux API is funky enough as is, so let's try to make it as fun to use as possible :)

Cheers!

**Comment by Papierkorb** [comment]
Addendum, if you want to get to work, I'll wait for the PR(s) before releasing all of it.
